name: Notify

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened, edited, deleted, closed, labeled, milestoned]
  issue_comment:
  gollum:
  discussion:
  discussion_comment:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"

      - name: start-build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "PR Comment\n触发事件：${{github.event_name}}\n提交人：${{github.actor}}","tag": "lark_md"}}]}}'

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request && github.event_name == "issue_comment" }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"

      - name: official notify
        env:
          LABELS: ${{ toJson(github.event.issue.labels) }}
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"header": {"title": {"tag": "plain_text", "content": "NOTIFY: issue ${{ github.event.issue.number }} comment ${{ github.event.comment.id }} ${{ github.event.action }}"}}, "config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "- **repository name**: ${{ github.event.repository.name }}\n- **issue title**: ${{ github.event.issue.title }}\n- **comment body**: ${{ github.event.comment.body }}\n- **issue comment link:** [open issue comment](${{ github.event.comment.html_url }})\n- **issue state**: ${{ github.event.issue.state }}\n- **assignee:** ${{ github.event.issue.assignee }} \n- **assignees:** ${{ github.event.issue.assignees }} \n- **issue labels**: ${{ github.event.issue.labels }}\n- **issue comment author:** ${{github.actor}}\n- **created at:** ${{ github.event.issue.created_at }}\n- **updated at:** ${{ github.event.issue.updated_at }}","tag": "lark_md"}}]}}'

  issue_action:
    name: Issue Created
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: official notify
        env:
          LABELS: ${{ toJson(github.event.issue.labels) }}
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"header": {"title": {"tag": "plain_text", "content": "NOTIFY: issue ${{ github.event.issue.number }} ${{ github.event.action }}"}}, "config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "**repository**: ${{ github.event.repository.name }}\n**issue title**: ${{ github.event.issue.title }}\n**issue body**: ${{ github.event.issue.body }}\n- **issue state**: ${{ github.event.issue.state }}\n- **assignee:** ${{ github.event.issue.assignee }} \n- **assignees:** ${{ github.event.issue.assignees }} \n- **issue labels**: ${{ github.event.issue.labels }}\n- **issue author:** ${{github.actor}} \n- **created at:** ${{ github.event.issue.created_at }}\n- **updated at:** ${{ github.event.issue.updated_at }}\n","tag": "lark_md"}}, {"tag":"button", "text":{ "tag":"lark_md", "content":"open issue" }, "url":"${{ github.event.issue.html_url }}", "type":"primary"} ]}}'
