name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Stale issue message'
          stale-pr-message: 'Stale pull request message'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'

      - name: notify
        env:
          LABELS: ${{ toJson(github.event.issue.labels) }}
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          body: '{"msg_type": "interactive","card": {"header": {"title": {"tag": "plain_text", "content": "Repository Popularity Statistice Notify"}}, "config": {"wide_screen_mode": true,"enable_forward": true},"elements": [{"tag": "div","text": {"content": "**repository: **${{ github.repository.full_name }}\n**star: ** ${{ github.repository.stargazers_count }}\n**fork: **${{ github.repository.forks }}\n**issue count: **${{ github.repository.open_issues }}\n","tag": "lark_md"}}]}}'

